services:
  database:
    image: postgres
    restart: always
    shm_size: 512mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: